### PR TITLE
Wifi coex

### PR DESCRIPTION
**Pull request by JochenFriedrich**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [x] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by JochenFriedrich** [comment]
Allows zigbee and WiFi coexisting on Esp32c6 hardware.

**Comment by JochenFriedrich** [comment]
See https://github.com/espressif/esp-zigbee-sdk/issues/415

**Comment by luar123** [comment]
Thank you! Do you think it would make sense to remove the option and to add the define automatically if the wifi component is detected?

**Comment by JochenFriedrich** [comment]
Yes, this might be an idea. Configuring both wifi and zigbee makes no sense without this option.

**Comment by luar123** [comment]
I messed-up this PR with re-basing, so I added your commit directly. Also added small modifications. The `CONFIG_WIFI_COEX` define is something you came up with and it is not used by esp-idf components, correct?
Please test and let me know if there is an issue.

For the future I want to maintain the zigbee component only in the esphome_zigbee repository (this here creates too much overhead). Please submit next PRs to https://github.com/luar123/zigbee_esphome

**Pull request closed without merging**
